create table if not exists new_products (
  id bigint generated by default as identity primary key,
  sku text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
